import mongoose, { Schema, Document } from "mongoose";

export interface IInterviewQuestion extends Document {
  interviewId: mongoose.Types.ObjectId;

  question: string;

  category: string;

  difficulty: "easy" | "medium" | "hard";

  answer?: string;

  // New fields for supporting Audio & Video interview entries
  answerType?: "text" | "audio" | "video";

  transcript?: string;

  audioUrl?: string;

  videoUrl?: string;

  feedback?: string;

  score?: number;

  communicationScore?: number;

  technicalAccuracyScore?: number;

  confidenceScore?: number;

  completenessScore?: number;

  structureScore?: number;

  // New communication metrics
  clarityScore?: number;

  fluencyScore?: number;

  improvedAnswer?: string;

  strengths?: string[];

  weaknesses?: string[];

  followUps?: string[];
}

const InterviewQuestionSchema =
  new Schema<IInterviewQuestion>(
    {
      interviewId: {
        type: Schema.Types.ObjectId,
        ref: "Interview",
        required: true,
      },

      question: {
        type: String,
        required: true,
      },

      category: {
        type: String,
        required: true,
      },

      difficulty: {
        type: String,
        enum: ["easy", "medium", "hard"],
        default: "medium",
      },

      answer: String,

      answerType: {
        type: String,
        enum: ["text", "audio", "video"],
        default: "text",
      },

      transcript: String,

      audioUrl: String,

      videoUrl: String,

      feedback: String,

      score: Number,

      communicationScore: Number,

      technicalAccuracyScore: Number,

      confidenceScore: Number,

      completenessScore: Number,

      structureScore: Number,

      clarityScore: Number,

      fluencyScore: Number,

      improvedAnswer: String,

      strengths: [String],

      weaknesses: [String],

      followUps: [String],
    },
    {
      timestamps: true,
    }
  );

export default mongoose.models.InterviewQuestion ||
  mongoose.model<IInterviewQuestion>(
    "InterviewQuestion",
    InterviewQuestionSchema
  );

/**
 * FILE PURPOSE & HELP:
 * This model defines the schema for individual questions mapped to a specific interview session.
 * It has been updated to support the Audio & Video Interview System by including:
 * - `answerType`: Specifies the submission format ("text", "audio", or "video").
 * - `transcript`: Stashes the speech-to-text representation generated by Groq Whisper from candidate audio/video recordings.
 * - `audioUrl` & `videoUrl`: References the secure media URLs generated after uploading the recorded Blobs to Cloudinary.
 *
 * It also supports granular AI evaluation metrics across 7 dimensions:
 * - Technical Accuracy, Communication, Confidence, Completeness, Structure (original 5 metrics)
 * - Clarity and Fluency (new metrics added for advanced speech analysis in Phase 3)
 * Storing these metrics makes it easy to construct a dashboard visualising the candidate's detailed score.
 *
 * FLOW INVOLVEMENT:
 * 1. Generated in POST /api/interviews (empty answer/metrics)
 * 2. Filled in POST /api/interviews/questions/[questionId]/answer (stores type, media links, transcript, and AI evaluation output)
 * 3. Read in GET /api/interviews/[id]/questions (conduct screen) and GET /api/interviews/[id] (summary report page)
 */